version: '3.8'

services:
  bot:
    build: .
    container_name: binance-trading-bot
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: bot-database
    environment:
      POSTGRES_DB: trading_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: